# Generated by Django 4.2.7 on 2023-11-23 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firstname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Patronymic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Surname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=20)),
                ('corpus', models.CharField(max_length=10)),
                ('apartments', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=25)),
                ('firstname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone_directory.firstname')),
                ('patronymic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone_directory.patronymic')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone_directory.street')),
                ('surname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone_directory.surname')),
            ],
        ),
    ]
