# Generated by Django 4.2.7 on 2023-11-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='firstname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phone_directory.firstname'),
        ),
        migrations.AlterField(
            model_name='main',
            name='patronymic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phone_directory.patronymic'),
        ),
        migrations.AlterField(
            model_name='main',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phone_directory.street'),
        ),
        migrations.AlterField(
            model_name='main',
            name='surname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='phone_directory.surname'),
        ),
    ]
